# Generated by Django 6.1 on 2026-08-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='found_items/')),
                ('item_type', models.CharField(blank=True, max_length=100)),
                ('primary_color', models.CharField(blank=True, max_length=50)),
                ('secondary_colors', models.JSONField(blank=True, default=list)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('distinguishing_features', models.JSONField(blank=True, default=list)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('date_found', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
