# Generated by Django 6.1 on 2026-08-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditem',
            name='item_type',
        ),
        migrations.AddField(
            model_name='founditem',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
